name: Test commit
on: [push]
jobs:
  changed:
    runs-on: ubuntu-latest
    outputs:
      composer: ${{ steps.code.outputs.matched_files }}
      php: ${{ steps.code.outputs.filtered_diff }}
      composer-lock-hash: ${{ steps.md5.outputs.composer-lock-hash }}
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v6
        id: code
        with:
          PATTERNS: |
            +(src)/**/*.php
          FILES: |
            composer.lock
      -
        id: md5
        run: (printf %s "composer-lock-hash=" >> $GITHUB_OUTPUT && md5sum composer.lock | awk '{ print $1 }' >> $GITHUB_OUTPUT)
  repository-name:
    runs-on: ubuntu-latest
    outputs:
      slug: ${{ steps.repo_slug.outputs.result }}
    steps:
      - name: Sanitize repo slug
        uses: actions/github-script@v6
        id: repo_slug
        with:
          result-encoding: string
          script: return 'ghcr.io/${{ github.repository }}'.toLowerCase()
  build-image:
    needs: [ changed, repository-name ]
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_REGISTRY_GITHUB }}
      - name: Build dependency Image
        if: ${{ needs.changed.outputs.composer }}
        uses: docker/build-push-action@v3
        with:
          target: composerdependency
          build-args: |
            COMPOSER_LOCK_HASH=${{needs.changed.outputs.composer-lock-hash}}
          cache-from: ${{ needs.repository-name.outputs.slug}}/ci/dependency:${{needs.changed.outputs.composer-lock-hash}}
          cache-to: ${{ needs.repository-name.outputs.slug}}/ci/dependency:${{needs.changed.outputs.composer-lock-hash}}
          push: true
          pull: true
          file: .docker/Dockerfile.ci
          tags: ${{ needs.repository-name.outputs.slug}}/ci/dependency:${{needs.changed.outputs.composer-lock-hash}}
      -
        name: Build and push CI Image
        uses: docker/build-push-action@v3
        with:
          build-args: |
            COMPOSER_LOCK_HASH=${{needs.changed.outputs.composer-lock-hash}}
          cache-from: ${{ needs.repository-name.outputs.slug}}/ci/dependency:${{needs.changed.outputs.composer-lock-hash}}
          push: true
          file: .docker/Dockerfile.ci
          tags: ${{ needs.repository-name.outputs.slug}}/ci:${{github.sha}}

  run-phpunit:
    needs: [build-image, repository-name]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /app
    container:
      image: ${{ needs.repository-name.outputs.slug}}/ci:${{github.sha}}
      volumes:
       - ${{github.WORKSPACE}}/.output/:/app/.output
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_REGISTRY_GITHUB }}
      env:
        XDEBUG_MODE: coverage
    steps:
      - name: RUN phpunit
        run: (ls -al && ls .output/ -al && vendor/bin/phpunit --coverage-php .output/coverage.cov)
      - uses: pCYSl5EDgo/cat@master
        id: hello
        with:
          path: ${{github.WORKSPACE}}/.output/coverage.cov
      - run: echo $TEXT
        env:
          TEXT: ${{ steps.hello.outputs.text }}
      - uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: phpunit-coverage-report
          path: .output/coverage.cov

  git-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: (git diff HEAD^1 > .output/patch.txt)
      - uses: actions/upload-artifact@v3
        with:
          name: git-diff
          path: .output/patch.txt
      - name: "Check for BC breaks"
        uses: docker://nyholm/roave-bc-check-ga

  run-coverage-check:
    if: ${{ needs.changed.outputs.php }}
    needs:
      - changed
      - run-phpunit
      - git-diff
    runs-on: ubuntu-latest
    container:
      image: fearofcode/phpcov:8
      volumes:
        - ${{github.WORKSPACE}}/:${{github.WORKSPACE}}
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: git-diff
      - uses: actions/download-artifact@v2
        with:
          name: phpunit-coverage-report
      - run: (phpcov patch-coverage --path-prefix /app coverage.cov patch.txt)

  run-psalm:
    needs: [build-image, repository-name]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /app
    container:
      image: ${{ needs.repository-name.outputs.slug}}/ci:${{github.sha}}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_REGISTRY_GITHUB }}
      env:
        XDEBUG_MODE: coverage
    steps:
      - name: RUN psalm
        run: (psalm)